version: '3.6'

services:

  postgres:
    ports:
      - 5432:5432

  mongodb:
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
      
  mysql:
    ports:
      - 3306:3306
     
