version: '3'

volumes:
  mongo-volume:
    driver: local
  formio-volume:
    driver: local
  bonita-volume:
    driver: local
  bonitad-volume:
    driver: local
  postgres-volume:
    driver: local
  alfresco-volume:
    driver: local


services:

  postgres:
    image: postgres
    volumes:
     - postgres-volume:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD={--postgres_password--}
    command:
      - -c
      - max_prepared_transactions=100

  mongodb:
    image: mongo
    volumes:
      - mongo-volume:/data/db

  formio-api:
    image: skarvelis/formio-api:1.0
    ports:
      - 3001:3001
    environment:
      - VIRTUAL_HOST={--formio_host--}
      - REVERSE_PROXY=false
      - DB_HOST=mongodb
      - DB_NAME=formio
      - ADMIN_EMAIL={--formio_admin_email--}
      - ADMIN_PASS={--formio_admin_password--}
    depends_on:
      - mongodb
    volumes:
      - formio-volume:/app

  bonita:
    image: bonita
    ports:
      - 9090:8080
    environment:
      - POSTGRES_ENV_POSTGRES_PASSWORD={--postgres_password--}
      - DB_VENDOR=postgres
      - DB_HOST=postgres
      - TENANT_LOGIN={--bonita_tenant_login--}
      - TENANT_PASSWORD={--bonita_tenant_password--}
      - PLATFORM_LOGIN={--bonita_platform_login--}
      - PLATFORM_PASSWORD={--bonita_platform_password--}
      - HTTP_API=true
    depends_on:
      - postgres
    volumes:
      - bonita-volume:/opt/bonita
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Waiting for Postgres to be available'
        export PGPASSWORD="$$POSTGRES_ENV_POSTGRES_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! psql -h "$$DB_HOST" -U 'postgres' -c '\l'; do
            let maxTries--
            sleep 1
        done
        echo
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error: unable to contact Postgres after 10 tries'
            exit 1
        fi
        exec /opt/files/startup.sh

  bonita-desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - 6080:80
      - 5900:5900
      - 10000:8080
    environment: 
      - VNC_PASSWORD={--bd_vnc_password--}
      - USER={--bd_user--} 
      - PASSWORD={--bd_password--}
    volumes:
      - bonitad-volume:/home/{--bd_user--}

  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./obif/:/home/node/app
    ports:
      - 10631:10631
    command: "npm start"

  alfresco:
       image: "pdubois/docker-alfresco:master"
       ports:
        - 8450:8443
       volumes:
        - alfresco-volume:/opt/alfresco/alf_data
       environment:
        - INITIAL_PASS={--alfresco_password--}
        - CONTAINER_FUNCTION=tomcat
        - ALF_1=db.url.EQ.jdbc:postgresql:\/\/postgres:5432\/alfresco
        - ALF_2=db.password.EQ.{--postgres_password--}  
        - ALF_3=db.username.EQ.postgres
        - DB_CONTAINER_NAME=postgres
       depends_on:
        - postgres
