version: '3.6'

volumes:
  vpn-volume:
    driver: local
    
networks:
  obi_net:
    external: true

services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    networks:
      - obi_net
    ports:
     - "1194:1194/udp"
    volumes:
     - vpn-volume:/etc/openvpn
